config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :invoices do #, only: [:new, :update, :create, :edit]
    get 'add_to_cart', on: :member
    get 'claim', on: :member
  end

  resources :receipts
  resources :rewards
  resource :profile, only: [:edit, :update]

  get 'dashboard', to: 'home#dashboard'
  get 'vendor_dashboard', to: 'home#vendor_dashboard'

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :receipt
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :vendor
  belongs_to :category
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :vendor
  has_one :user
  has_many :line_items
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :vendors
  belongs_to :users
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :receipts
  has_many :rewards
  has_one :vendor

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:consumer) if self.roles.blank?
  end
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :receipts
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      # redirect to vendor or consumer
      #super
      if resource.has_role? :vendor 
        vendor_dashboard_path
      else
        dashboard_path
      end
    else
      stored_location_for(resource) || request.referer || root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render layout: "homepage"
  end

  def dashboard
    @header = "Dashboard"
  end

  def vendor_dashboard
    @header = "Dashboard"
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_vendor, except: [:claim]
  before_action :load_receipt, only: [:edit, :update, :add_to_cart, :show, :claim]

  def new
    @invoice = @vendor.receipts.create
    redirect_to edit_invoice_path(@invoice)
  end

  def edit
    @header = "Sales"
    @products = @vendor.products
  end

  def update
  end

  def show
    @header = "Sales"
    @qrcode = RQRCode::QRCode.new(claim_invoice_url(@invoice), :size => 6, :level => :h)
  end

  def add_to_cart
    product = Product.find(params[:product_id])
    @invoice.line_items.create({
      description: product.name,
      price: product.price,
      quantity: 1,
      sku: product.sku
    })

    redirect_to edit_invoice_path(@invoice)
  end

  def claim
    if current_user.has_role?(:consumer)
      flash[:success] = 'Receipt successfully claimed'
      @invoice.user_id = current_user
      @invoice.save
    else
      flash[:warning] = 'Invalid receipt barcode'
      redirect_to root_url
    end
  end


  private

  def load_vendor
    @vendor = Vendor.find(current_user.vendor_id)
  end

  def load_receipt
    @invoice = Receipt.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def edit
    @header = "Profile"
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:notice] = 'Profile updated successfully'
    else
      flash[:notice] = 'There was a problem saving your profile'
    end
    render :edit
  end

  private 
  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :country, :city, :postal_code)
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :authenticate_user!

  def index
    @header = "Receipts"
  end

  def show
    @header = "Receipts"
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @header = "Rewards"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-danger"
    end
  end
  
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ''
  end

  def user_type(user)
    if user.has_role? :vendor 
      'vendor'
    else
      'consumer'
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/receipt_helper.rb
module ReceiptHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/home/index.html.erb
<body id="top">
    <header>
      <!-- Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" id="navbar">
        <div class="container"><a class="navbar-brand" href="#"><strong>Payceipt</strong></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a class="nav-link active" href="#about">About</a></li>
              <li class="nav-item"><a class="nav-link" href="#pricing">Pricing</a></li>
            <% if user_signed_in? %>
              <% if current_user.has_role? :vendor  %>
                <li class="nav-item"><a class="nav-link" href="<%= vendor_dashboard_path %>">Dashboard</a></li>
              <% else %>
                <li class="nav-item"><a class="nav-link" href="<%= dashboard_path %>">Dashboard</a></li>
              <% end %>
            <li class="nav-item"><%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %></li>
            <% else %>
            <li class="nav-item"><%= link_to('Login', new_user_session_path, class: "nav-link") %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <!-- Intro Section-->
      <section class="view hm-gradient" id="intro">
        <div class="full-bg-img d-flex align-items-center">
          <div class="container">
            <div class="row no-gutters">
              <div class="col-md-10 col-lg-6 text-center text-md-left margins">
                <div class="white-text">
                  <div class="wow fadeInLeft" data-wow-delay="0.3s">
                    <h1 class="h1-responsive font-bold mt-sm-5">Cashless. Paperless. Effortless.</h1>
                    <div class="h6">
                      Introducing a unified platform where users are can easily subscribed to the business marketing and promotion by scanning their receipt where it can also help them track their expenses and enjoy the brand’s promotional offers.
                    </div>
                  </div><br>
                  <div class="wow fadeInLeft" data-wow-delay="0.3s"><a class="btn btn-white dark-grey-text font-bold ml-0" href="https://www.youtube.com/watch?v=Keo9WQXSVFc" target="_blank"><i class="fa fa-play mr-1"></i> View Demo</a>
                  <%# <a class="btn btn-outline-white" href="#">Learn more</a> %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </header>
    <div id="content">
<section class="row no-gutters" id="features">
  <div class="col-lg-3 col-md-6 col-sm-12 deep-purple lighten-1 text-white">
    <div class="p-5 text-center wow zoomIn" data-wow-delay=".1s"><i class="fa fa-line-chart fa-2x"></i>
      <div class="h5 mt-3">Consumer Analytics</div>
      <p class="mt-5">Payceipt provides insights into your consumer spending behaviour</p>
    </div>
  </div>
  <div class="col-lg-3 col-md-6 purple lighten-1 text-white">
    <div class="p-5 text-center wow zoomIn" data-wow-delay=".3s"><i class="fa fa-industry fa-2x"></i>
      <div class="h5 mt-3">Loyalty Programs</div>
      <p class="mt-5">Seamlessly enrol your customers into loyalty programs and reward them based on their purchases</p>
    </div>
  </div>
  <div class="col-lg-3 col-md-6 teal lighten-1 text-white">
    <div class="p-5 text-center wow zoomIn" data-wow-delay=".5s"><i class="fa fa-users fa-2x"></i>
      <div class="h5 mt-3">Build Customer Trust</div>
      <p class="mt-5">Using Payceipt, we provide anonymous analytic data to retailers thus ensuring customer privacy and eagerness to use the platform</p>
    </div>
  </div>
  <div class="col-lg-3 col-md-6 light-blue lighten-1 text-white">
    <div class="p-5 text-center wow zoomIn" data-wow-delay=".7s"><i class="fa fa-bullhorn fa-2x"></i>
      <div class="h5 mt-3">Post Purchase</div>
      <p class="mt-5">Payceipt provides a platform for retailers to engage with their customers post sale</p>
    </div>
  </div>
</section>
<section class="text-center py-5 grey lighten-4" id="about">
  <div class="container">
    <div class="wow fadeIn">
      <h2 class="h1 pt-5 pb-3">Why use Payceipt?</h2>
      <p class="px-5 mb-5 pb-3 lead blue-grey-text">
        With our innovative approach to building customer relationships through the use of QR receipt scanning and providing tools for customers to more effectively manage their spendings and make the most informed purchase decision, we believe we can drive more quality customers to retailers.
      </p>
    </div>
    <div class="row">
      <div class="col-md-4 mb-r wow fadeInUp" data-wow-delay=".3s"><i class="fa fa-dashboard fa-3x orange-text"></i>
        <h3 class="h4 mt-3">Ease of Use</h3>
        <p class="mt-3 blue-grey-text">
          Our platform offers a world class user friendly interface for generating the digital receipts for customers
        </p>
      </div>
      <div class="col-md-4 mb-r wow fadeInUp" data-wow-delay=".4s"><i class="fa fa-comments-o fa-3x cyan-text"></i>
        <h3 class="h4 mt-3">Engaging</h3>
        <p class="mt-3 blue-grey-text">
          Engage with your customers directly through our platform by publishing special offers and promotions
        </p>
      </div>
      <div class="col-md-4 mb-r wow fadeInUp" data-wow-delay=".5s"><i class="fa fa-cubes fa-3x red-text"></i>
        <h3 class="h4 mt-3">Extensible</h3>
        <p class="mt-3 blue-grey-text">
          Our platform allows extensibility to provide more advanced customer engagement tools
        </p>
      </div>
    </div>
  </div>
</section>

<section class="text-center py-5 indigo darken-1 text-white" id="pricing">
  <div class="container">
    <div class="wow fadeIn">
      <h2 class="h1 pt-5 pb-3">Our pricing plans</h2>
      <p class="px-5 mb-5 pb-3 lead">
        We offer affordable packages for different size of business with the option of partnering with a Point of Sale provider for a complete retail solution.
      </p>
    </div>
    <div class="row wow zoomIn">
      <div class="col-lg-4 col-md-12 mb-r">
        <div class="card card-image">
          <div class="text-white text-center pricing-card d-flex align-items-center rgba-stylish-strong py-3 px-3 rounded">
            <div class="card-body">
              <div class="h5">Individual</div>
              <div class="py-5"><sup class="display-4">MYR</sup><span class="display-3">50</span><span class="display-4">/m</span></div>
              <ul class="list-unstyled">
                <li>
                  <p><strong>1</strong> license</p>
                </li>
                <li>
                  <p><strong>2,000</strong> receipts</p>
                </li>
                <li>
                  <p><strong>1,000</strong> customers</p>
                </li>
              </ul><a class="btn btn-outline-white mt-5"> Subscribe now</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-12 mb-r">
        <div class="card card-image">
          <div class="text-white text-center pricing-card d-flex align-items-center rgba-teal-strong py-3 px-3 rounded">
            <div class="card-body">
              <div class="h5">Startup</div>
              <div class="py-5"><sup class="display-4">MYR</sup><span class="display-3">299</span><span class="display-4">/m</span></div>
              <ul class="list-unstyled">
                <li>
                  <p><strong>50</strong> license</p>
                </li>
                <li>
                  <p><strong>20,000</strong> receipts</p>
                </li>
                <li>
                  <p><strong>10,000</strong> customers</p>
                </li>
              </ul><a class="btn btn-outline-white mt-5"> Subscribe now</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-12 mb-r">
        <div class="card card-image">
          <div class="text-white text-center pricing-card d-flex align-items-center rgba-red-strong py-3 px-3 rounded">
            <div class="card-body">
              <div class="h5">Enterprise</div>
              <div class="py-5"><sup class="display-4">MYR</sup><span class="display-3">499</span><span class="display-4">/m</span></div>
              <ul class="list-unstyled">
                <li>
                  <p><strong>Unlimited</strong> license</p>
                </li>
                <li>
                  <p><strong>Unlimited</strong> receipts</p>
                </li>
                <li>
                  <p><strong>Unlimited</strong> customers</p>
                </li>
              </ul><a class="btn btn-outline-white mt-5"> Subscribe now</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<%# <section class="py-5" id="team">
  <div class="container">
    <div class="wow fadeIn">
      <h2 class="h1 pt-5 pb-3 text-center">Our team members</h2>
      <p class="px-5 mb-5 pb-3 lead text-center blue-grey-text">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error amet numquam iure provident voluptate
        esse quasi, veritatis totam voluptas nostrum quisquam eum porro a pariatur accusamus veniam.
      </p>
    </div>
    <div class="row mb-lg-4 center-on-small-only">
      <div class="col-lg-6 col-md-12 mb-r wow fadeInLeft" data-wow-delay=".3s">
        <div class="col-md-6 float-left"><img class="img-fluid rounded z-depth-1 mb-3" src="img/woman-1.jpg" alt="team member"/></div>
        <div class="col-md-6 float-right">
          <div class="h4">Ng Soon Chi</div>
          <h6 class="font-bold blue-grey-text mb-4">Graphic Designer</h6>
          <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eos id officiis hic tenetur.</p><a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i><span class="ml-1">@nicolewest</span></a>
        </div>
      </div>
      <div class="col-lg-6 col-md-12 mb-r wow fadeInRight" data-wow-delay=".3s">
        <div class="col-md-6 float-left"><img class="img-fluid rounded z-depth-1 mb-3" src="img/woman-2.jpg" alt="team member"/></div>
        <div class="col-md-6 float-right">
          <div class="h4">Hannah Cruz</div>
          <h6 class="font-bold blue-grey-text mb-4">Photographer</h6>
          <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eos id officiis hic tenetur.</p><a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i><span class="ml-1">@hannahcruz</span></a>
        </div>
      </div>
    </div>
    <div class="row center-on-small-only">
      <div class="col-lg-6 col-md-12 mb-r wow fadeInLeft" data-wow-delay=".3s">
        <div class="col-md-6 float-left"><img class="img-fluid rounded z-depth-1 mb-3" src="img/man-1.jpg" alt="team member"/></div>
        <div class="col-md-6 float-right">
          <div class="h4">Mark Hall</div>
          <h6 class="font-bold blue-grey-text mb-4">Web Developer</h6>
          <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eos id officiis hic tenetur.</p><a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i><span class="ml-1">@markhall</span></a>
        </div>
      </div>
      <div class="col-lg-6 col-md-12 mb-r wow fadeInRight" data-wow-delay=".3s">
        <div class="col-md-6 float-left"><img class="img-fluid rounded z-depth-1 mb-3" src="img/man-2.jpg" alt="team member"/></div>
        <div class="col-md-6 float-right">
          <div class="h4">Vincent Harris</div>
          <h6 class="font-bold blue-grey-text mb-4">Web Developer</h6>
          <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eos id officiis hic tenetur.</p><a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i><span class="ml-1">@vincentharris</span></a>
        </div>
      </div>
          <div class="row mb-lg-4 center-on-small-only">
      <div class="col-lg-6 col-md-12 mb-r wow fadeInLeft" data-wow-delay=".3s">
        <div class="col-md-6 float-left"><img class="img-fluid rounded z-depth-1 mb-3" src="img/woman-1.jpg" alt="team member"/></div>
        <div class="col-md-6 float-right">
          <div class="h4">Nicole West</div>
          <h6 class="font-bold blue-grey-text mb-4">Lead Designer</h6>
          <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eos id officiis hic tenetur.</p><a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i><span class="ml-1">@nicolewest</span></a>
        </div>
      </div>
    </div>
    </div>
  </div>
</section> %>
</div>

app/views/invoices/claim.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title ">Receipt No <%= @invoice.id %></h4>
        <p class="card-category"> <%= @invoice.vendor.name %></p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th>
                Item
              </th>
              <th>
                Price
              </th>
            </thead>
            <tbody>
              <% @invoice.line_items.each do |line_item| %>
                <tr>
                  <td>
                    <%= line_item.description %>
                  </td>
                  <td class="text-primary">
                    <%= number_to_currency(line_item.price) %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td>Total</td>
                <td class="text-primary"><strong><%= number_to_currency(@invoice.line_items.sum(:price)) %></strong></td>
              </tr>
            </tbody>
          </table>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title ">Menu</h4>
        <p class="card-category"> Here is a subtitle for this table</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th>
                Name
              </th>
              <th>
                Price
              </th>
              <th>
                
              </th>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td>
                    <%= product.name %>
                  </td>
                  <td class="text-primary">
                    <%= number_to_currency(product.price) %>
                  </td>
                  <td>
                    <%= link_to "Add To Cart", add_to_cart_invoice_path(product_id: product.id), class: "btn btn-primary pull-right" %>
                    <!-- <button type="button" class=""></button>-->
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title ">Order No <%= @invoice.id %></h4>
        <p class="card-category"> Here is a subtitle for this table</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th>
                Name
              </th>
              <th>
                Price
              </th>
            </thead>
            <tbody>
              <% @invoice.line_items.each do |line_item| %>
                <tr>
                  <td>
                    <%= line_item.description %>
                  </td>
                  <td class="text-primary">
                    <%= number_to_currency(line_item.price) %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td>Total</td>
                <td class="text-primary"><%= number_to_currency(@invoice.line_items.sum(:price)) %></td>
              </tr>
            </tbody>
          </table>
          </div>

          <%= link_to "Close Sale", invoice_path(@invoice), class: "btn btn-primary pull-right" %>
      </div>
    </div>
  </div>

</div>

app/views/invoices/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="barcode">
        <%= raw @qrcode.as_html %>
    </div>
    </div>
  </div>
  </div>
<div class="row">
  <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title ">Order No <%= @invoice.id %></h4>
          <p class="card-category"> <%= @invoice.vendor.name %></p>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <th>
                  Name
                </th>
                <th>
                  Price
                </th>
              </thead>
              <tbody>
                <% @invoice.line_items.each do |line_item| %>
                  <tr>
                    <td>
                      <%= line_item.description %>
                    </td>
                    <td class="text-primary">
                      <%= number_to_currency(line_item.price) %>
                    </td>
                  </tr>
                <% end %>
                <tr>
                  <td>Total</td>
                  <td class="text-primary"><strong><%= number_to_currency(@invoice.line_items.sum(:price)) %></strong></td>
                </tr>
              </tbody>
            </table>
            </div>
        </div>
      </div>
    </div>
</div>

app/views/profiles/edit.html.erb
<div class="row">
<div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Edit Profile</h4>
                  <p class="card-category">Complete your profile</p>
                </div>
                <div class="card-body">
                  <%= form_for @user, url: {action: "update", controller: 'profiles'} do |form| %>
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Email address</label>
                          <%= form.text_field :email, class: 'form-control', disabled: true %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Fist Name</label>
                          <%= form.text_field :first_name, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Last Name</label>
                          <%= form.text_field :last_name, class: 'form-control' %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Address</label>
                          <%= form.text_area :address, class: 'form-control' %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">City</label>
                          <%= form.text_field :city, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Country</label>
                          <%= form.text_field :country, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Postal Code</label>
                          <%= form.text_field :postal_code, class: 'form-control' %>
                        </div>
                      </div>
                    </div>
                     <%= form.submit "Update Profile", class: "btn btn-primary pull-right" %>
                    <!-- <button type="submit" class="btn btn-primary pull-right">Update Profile</button>-->
                    <div class="clearfix"></div>
                  <% end %>
                </div>
              </div>
            </div>
            </div>

app/views/receipts/claim.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title ">Order No <%= @receipt.id %></h4>
        <p class="card-category"> Here is a subtitle for this table</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th>
                Item
              </th>
              <th>
                Price
              </th>
            </thead>
            <tbody>
              <% @receipt.line_items.each do |line_item| %>
                <tr>
                  <td>
                    <%= line_item.description %>
                  </td>
                  <td class="text-primary">
                    <%= number_to_currency(line_item.price) %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td>Total</td>
                <td class="text-primary"><%= number_to_currency(@receipt.line_items.sum(:price)) %></td>
              </tr>
            </tbody>
          </table>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/receipts/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title ">Menu</h4>
        <p class="card-category"> Here is a subtitle for this table</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th>
                Name
              </th>
              <th>
                Price
              </th>
              <th>
                
              </th>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td>
                    <%= product.name %>
                  </td>
                  <td class="text-primary">
                    <%= number_to_currency(product.price) %>
                  </td>
                  <td>
                    <%= link_to "Add To Cart", add_to_cart_receipt_path(product_id: product.id), class: "btn btn-primary pull-right" %>
                    <!-- <button type="button" class=""></button>-->
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title ">Order No <%= @receipt.id %></h4>
        <p class="card-category"> Here is a subtitle for this table</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th>
                Name
              </th>
              <th>
                Price
              </th>
            </thead>
            <tbody>
              <% @receipt.line_items.each do |line_item| %>
                <tr>
                  <td>
                    <%= line_item.description %>
                  </td>
                  <td class="text-primary">
                    <%= number_to_currency(line_item.price) %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td>Total</td>
                <td class="text-primary"><%= number_to_currency(@receipt.line_items.sum(:price)) %></td>
              </tr>
            </tbody>
          </table>
          </div>

          <%= link_to "Close Sale", receipt_path(@receipt), class: "btn btn-primary pull-right" %>
      </div>
    </div>
  </div>

</div>