config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :invoices do #, only: [:new, :update, :create, :edit]
    get 'add_to_cart', on: :member
    get 'claim', on: :member
  end

  resources :receipts
  resources :rewards
  resource :profile, only: [:edit, :update]

  get 'dashboard', to: 'home#dashboard'
  get 'vendor_dashboard', to: 'home#vendor_dashboard'

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :receipt
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :vendor
  belongs_to :category
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :vendor
  has_one :user
  has_many :line_items
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :vendors
  belongs_to :users
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :receipts
  has_many :rewards
  has_one :vendor

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:consumer) if self.roles.blank?
  end
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :receipts
  has_many :products
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render layout: "homepage"
  end

  def dashboard
    @header = "Dashboard"
  end

  def vendor_dashboard
    @header = "Dashboard"
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_vendor, except: [:claim]
  before_action :load_receipt, only: [:edit, :update, :add_to_cart, :show, :claim]

  def new
    @invoice = @vendor.receipts.create
    redirect_to edit_invoice_path(@invoice)
  end

  def edit
    @header = "Sales"
    @products = @vendor.products
  end

  def update
  end

  def show
    @header = "Sales"
    @qrcode = RQRCode::QRCode.new(claim_invoice_url(@invoice), :size => 6, :level => :h)
  end

  def add_to_cart
    product = Product.find(params[:product_id])
    @invoice.line_items.create({
      description: product.name,
      price: product.price,
      quantity: 1,
      sku: product.sku
    })

    redirect_to edit_invoice_path(@invoice)
  end

  def claim
    if current_user.has_role?(:consumer)
      flash[:success] = 'Receipt successfully claimed'
      @invoice.user_id = current_user
      @invoice.save
    else
      flash[:warning] = 'Invalid receipt barcode'
      redirect_to root_url
    end
  end


  private

  def load_vendor
    @vendor = Vendor.find(current_user.vendor_id)
  end

  def load_receipt
    @invoice = Receipt.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def edit
    @header = "Profile"
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:notice] = 'Profile updated successfully'
    else
      flash[:notice] = 'There was a problem saving your profile'
    end
    render :edit
  end

  private 
  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :country, :city, :postal_code)
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :authenticate_user!

  def index
    @header = "Receipts"
  end

  def show
    @header = "Receipts"
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @header = "Rewards"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-danger"
    end
  end
  
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ''
  end

  def user_type(user)
    if user.has_role? :vendor 
      'vendor'
    else
      'consumer'
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/receipt_helper.rb
module ReceiptHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payceipt - Innovating Beyond the Sale</title>
    <%= csrf_meta_tags %>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
 
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="">
    <div class="wrapper ">
      <%= render "layouts/#{user_type(current_user)}/sidebar" if user_signed_in?  %>
      <div class="main-panel">
        <%= render 'layouts/shared/navigation_bar' %>
        <div class="content">
          <div class="container-fluid">
            <% flash.each do |key, value| %>
              <div class="<%= flash_class(key) %>" role="alert">
                    <%= value %>
              </div>
            <% end %>
            <%= yield %>
          </div> <!-- container fluid -->
        </div>
        <%#= render 'layouts/shared/footer' %>
      </div>
    </div>

  <%= javascript_include_tag 'material/bootstrap-material-design.min' %>
  <%= javascript_include_tag 'material/perfect-scrollbar.jquery.min' %>
  <%= javascript_include_tag 'material/chartist.min' %>
  <%= javascript_include_tag 'material/bootstrap-notify' %>
  <%= javascript_include_tag 'material/material-dashboard.min' %>
  <%= javascript_include_tag 'material/demo' %>

    <script>
      $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        md.initDashboardPageCharts();
      });
    </script>
  </body>
</html>

app/views/layouts/consumer/_sidebar.html.erb
<div class="sidebar" data-color="green" data-background-color="white" data-image="<%= asset_path('sidebar-1.jpg')%>">
      <div class="logo">
        <a href="/" class="simple-text logo-normal">
          PayCeipt
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item <%= active_class(dashboard_path) %>">
            <a class="nav-link" href="<%= dashboard_path %>">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="nav-item <%= active_class(receipts_path) %>">
            <a class="nav-link" href="<%= receipts_path %>">
              <i class="material-icons">receipt</i>
              <p>Receipts</p>
            </a>
          </li>
          <li class="nav-item <%= active_class(rewards_path) %>">
            <a class="nav-link" href="<%= rewards_path %>">
              <i class="material-icons">card_giftcard</i>
              <p>Rewards</p>
            </a>
          </li>
          <li class="nav-item <%= active_class(edit_profile_path) %>">
            <a class="nav-link" href="<%= edit_profile_path %>">
              <i class="material-icons">person</i>
              <p>Profile</p>
            </a>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
              <i class="material-icons">exit_to_app</i>
              <p>Logout</p>
            <% end %>
          </li>
        </ul>
      </div>
    </div> 

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html class="full-height" lang="en-US">
  <head>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Payceipt - Innovating Beyond the Sale</title>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
    <meta name="description" content="Material design landing page template built by TemplateFlip.com"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'mdb/bootstrap.min', media: 'all' %>
    <%= stylesheet_link_tag 'mdb/mdb', media: 'all' %>
    <%= stylesheet_link_tag 'mdb/main', media: 'all' %>

  </head>
  <%= yield %>
    <footer class="page-footer indigo darken-2 center-on-small-only pt-0 mt-0">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="mb-5 flex-center"><a class="px-3"><i class="fa fa-facebook fa-lg white-text"></i></a><a class="px-3"><i class="fa fa-twitter fa-lg white-text"></i></a><a class="px-3"><i class="fa fa-google-plus fa-lg white-text"></i></a><a class="px-3"><i class="fa fa-linkedin fa-lg white-text"></i></a></div>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container-fluid">
          <p>&copy; <a href="/">Payceipt</a> 2018</p>
        </div>
      </div>
    </footer>
    <%= javascript_include_tag 'mdb/jquery-3.2.1.min' %>
    <%= javascript_include_tag 'mdb/popper.min' %>
    <%= javascript_include_tag 'mdb/bootstrap.min' %>
    <%= javascript_include_tag 'mdb/main' %>
    <%= javascript_include_tag 'mdb/mdb.min' %>
    
    <script>new WOW().init();</script>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <nav class="float-left">
      <ul>
        <li>
          <a href="https://www.creative-tim.com">
            Creative Tim
          </a>
        </li>
        <li>
          <a href="https://creative-tim.com/presentation">
            About Us
          </a>
        </li>
        <li>
          <a href="http://blog.creative-tim.com">
            Blog
          </a>
        </li>
        <li>
          <a href="https://www.creative-tim.com/license">
            Licenses
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright float-right">
      &copy; 2018, made with <i class="material-icons">favorite</i> by
      <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
    </div>
  </div>
</footer>

app/views/layouts/shared/_navigation_bar.backup.html.erb
<!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#">Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>

            <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path)  %>  
            <% end %>
            
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another Notification</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->

app/views/layouts/shared/_navigation_bar.html.erb
<!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#"><%= @header %></a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path)  %>  
            <% end %>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="<%= edit_profile_path %>">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->